# Generated by Django 2.2.10 on 2020-09-10 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepage',
            name='icon_classes',
            field=models.CharField(default='fas bolt', max_length=250),
            preserve_default=False,
        ),
    ]
