# Generated by Django 2.2.10 on 2020-10-10 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201010_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactdetail',
            name='annotation',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
