# Generated by Django 2.2.10 on 2020-10-19 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_administrationindexpage_administratorpage_councillorgrouppage_councillorlistpage_councillorpage_mymu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personpage',
            name='name',
        ),
    ]
