# Generated by Django 2.2.10 on 2020-10-19 16:12

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_personpage_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrationindexpage',
            name='overview',
            field=wagtail.core.fields.RichTextField(default=''),
            preserve_default=False,
        ),
    ]
