# Generated by Django 2.2.10 on 2020-10-22 11:40

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20201022_1037'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='politicalparty',
            options={'verbose_name_plural': 'Political parties'},
        ),
        migrations.AddField(
            model_name='personpage',
            name='job_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='personpage',
            name='overview',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
