# Generated by Django 2.2.10 on 2020-10-22 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0052_pagelogentry'),
        ('core', '0012_personpage_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepage',
            name='head_of_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
    ]
