# Generated by Django 2.2.10 on 2020-10-22 18:58

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0052_pagelogentry'),
        ('core', '0013_servicepage_head_of_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePointPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('overview', wagtail.core.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterField(
            model_name='servicepage',
            name='overview',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.CreateModel(
            name='ServicePointContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.ContactDetail')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_point_contacts', to='core.ServicePointPage')),
            ],
            options={
                'verbose_name': 'service point contact',
                'verbose_name_plural': 'service point contacts',
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
