# Generated by Django 2.2.10 on 2020-11-02 22:04

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20201023_0647'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepage',
            name='office_hours',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='servicepointpage',
            name='office_hours',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
