# Generated by Django 2.2.10 on 2020-11-02 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20201023_0647'),
    ]

    operations = [
        migrations.AddField(
            model_name='councillorgrouppage',
            name='icon_classes',
            field=models.CharField(default=[], max_length=250),
            preserve_default=False,
        ),
    ]
