# Generated by Django 2.2.10 on 2020-11-03 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_councillorgrouppage_icon_classes'),
        ('core', '0017_auto_20201102_2204'),
    ]

    operations = [
    ]
