# Generated by Django 2.2.10 on 2020-11-17 20:55

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_webpush'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebPushNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('COMPLETED', 'Completed'), ('FAILED_INCOMPLETE', 'Failed incomplete')], default='QUEUED', max_length=20)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('url', models.URLField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='WebPushNotificationResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_code', models.IntegerField()),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webpushnotificationresults', to='core.WebPushNotification')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webpushsubscriptionresults', to='core.WebPushSubscription')),
            ],
        ),
    ]
