# Generated by Django 2.2.10 on 2020-11-18 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_webpushnotification_webpushnotificationresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webpushnotificationresult',
            name='status_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
