# Generated by Django 2.2.10 on 2020-11-30 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20201118_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webpushnotification',
            name='data',
        ),
    ]
