# Generated by Django 2.2.10 on 2020-12-04 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20201203_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='webpushsubscription',
            name='enabled',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
