# Generated by Django 2.2.10 on 2021-02-12 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_webpushsubscription_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webpushnotificationresult',
            name='notification',
        ),
        migrations.RemoveField(
            model_name='webpushnotificationresult',
            name='subscription',
        ),
        migrations.RemoveField(
            model_name='webpushsubscription',
            name='user',
        ),
        migrations.DeleteModel(
            name='WebPushNotification',
        ),
        migrations.DeleteModel(
            name='WebPushNotificationResult',
        ),
        migrations.DeleteModel(
            name='WebPushSubscription',
        ),
    ]
