# Generated by Django 2.2.10 on 2021-02-24 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_servicerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='collaborator_status',
            field=models.CharField(blank=True, choices=[('initial', 'Initial'), ('registered', 'Registered'), ('assigned', 'Assigned'), ('completed', 'Completed'), ('finalised', 'Finalised')], default=None, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('created', 'Created'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='queued', max_length=254),
        ),
    ]
