# Generated by Django 2.2.10 on 2021-03-10 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_auto_20210301_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='councillorlistpage',
            name='icon_classes',
            field=models.CharField(default='fas fa-users', max_length=250),
            preserve_default=False,
        ),
    ]
