# Generated by Django 2.2.10 on 2021-03-10 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_councillorlistpage_icon_classes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='councillorlistpage',
            name='icon_classes',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
