# Generated by Django 2.2.10 on 2021-03-25 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_contactspage_emergencycontact_nationalgovernmentcontact_provincialgovernmentcontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrationindexpage',
            name='icon_classes',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='contactspage',
            name='icon_classes',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='noticeindexpage',
            name='icon_classes',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='politicalrepsindexpage',
            name='icon_classes',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
