# Generated by Django 2.2.10 on 2021-04-21 08:11

from django.db import migrations, models
import django.db.models.deletion
import muni_portal.core.models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0037_auto_20210326_0554"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicerequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("queued", "Queued"),
                    ("created", "Created"),
                    ("assigned", "Assigned"),
                    ("completed", "Completed"),
                ],
                default="queued",
                max_length=254,
            ),
        ),
        migrations.CreateModel(
            name="ServiceRequestAttachment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "file",
                    models.FileField(
                        upload_to=muni_portal.core.models.service_request_attachment_file_path
                    ),
                ),
                ("exists_on_collaborator", models.BooleanField(default=False)),
                (
                    "service_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="core.ServiceRequest",
                    ),
                ),
            ],
        ),
    ]
