# Generated by Django 2.2.10 on 2021-04-16 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0052_pagelogentry'),
        ('core', '0037_auto_20210326_0554'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedirectorPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('icon_classes', models.CharField(blank=True, max_length=100)),
                ('redirect_to', models.URLField(help_text='The URL to redirect to')),
            ],
            options={
                'verbose_name': 'Redirector',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('created', 'Created'), ('assigned', 'Assigned'), ('completed', 'Completed')], default='queued', max_length=254),
        ),
    ]
