# Generated by Django 2.2.10 on 2021-04-30 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0038_auto_20210421_0811"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicerequestattachment",
            name="content_type",
            field=models.CharField(max_length=255),
            preserve_default=False,
        ),
    ]
