# Generated by Django 2.2.10 on 2021-05-07 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_auto_20210416_2115'),
        ('core', '0039_servicerequestattachment_content_type'),
    ]

    operations = [
    ]
