# Generated by Django 2.2.10 on 2021-05-25 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_merge_20210507_1507'),
        ('core', '0040_newsindexpage_newspage'),
    ]

    operations = [
    ]
