# Generated by Django 2.2.10 on 2021-05-30 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_auto_20210530_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspage',
            name='subtitle',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AddField(
            model_name='noticepage',
            name='subtitle',
            field=models.CharField(default='', max_length=512),
        ),
    ]
