# Generated by Django 2.2.10 on 2021-06-08 16:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('wagtailcore', '0052_pagelogentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('core', '0045_auto_20210608_1637'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PrivacyPolicy',
            new_name='PrivacyPolicyPage',
        ),
    ]
