languae: python
python:
  - "3.7"

install:
  - pip install poetry
  - poetry install
  # Allow the container user to write to this directory
  - export USER_ID=$(id -u) && export GROUP_ID=$(id -g)
  - docker-compose run --rm web yarn


before_script:
  - docker-compose run --rm web bin/wait-for-postgres.sh python manage.py migrate


script:
  - docker-compose run --rm web yarn build
  - docker-compose run --rm web python manage.py collectstatic --no-input
  - docker-compose run --rm web bin/wait-for-postgres.sh coverage run --source=muni_portal manage.py test

  # Ensure that the demodata fixture can be loaded and the data is available in the API
  # - smoke test
  # - ensure development environment setup is maintained.
  - docker-compose run --rm web bin/wait-for-postgres.sh python manage.py loaddata seeddata demodata
  - docker-compose up -d
  - wget --retry-connrefused --waitretry=1 --read-timeout=10 --timeout=10 --tries=10 -O-  "http://localhost:8000/api/wagtail/v2/pages/?type=core.ServicePage&fields=*" | grep "electrical"


after_script:
  # Log DB output in case issues occurred where this can help us debug quicly
  - docker-compose logs db

  # Upload code coverage data to codecov.io
  - "docker-compose run --rm `bash <(curl -s https://codecov.io/env)` web codecov"
