name: Test

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 0' # weekly

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Configure variables to run container under host user ID
        run: export USER_ID=$(id -u) && export GROUP_ID=$(id -g)

      - name: Run tests
        run: DJANGO_Q_SYNC=True docker-compose run --rm web bin/wait-for-postgres.sh coverage run --source=muni_portal manage.py test

      # Ensure that the demodata fixture can be loaded and the data is available in the API
      # - smoke test
      # - ensure development environment setup is maintained.
      - name: Run migrations to configure database with schema
        run: docker-compose run --rm web bin/wait-for-postgres.sh python manage.py migrate
      - name: Load demo data fixture
        run: docker-compose run --rm web bin/wait-for-postgres.sh python manage.py loaddata seeddata demodata
      - name: Start server
        run: docker-compose up -d
      - name: "Smoke test: Check that demo data is returned by typical request to server"
        run: wget --retry-connrefused --waitretry=1 --read-timeout=10 --timeout=10 --tries=10 -O-  "http://localhost:8000/api/wagtail/v2/pages/?type=core.ServicePage&fields=*" | grep "electrical"
